version: "3.8"
services:
  mysql-db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql
  postgresql-db:
    image: postgres:16
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=root1234
    ports:
      - '5432:5432'
    volumes:
      - postgresql-db-data:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: carrizoaagustin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: zeus
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  mysql-db-data:
  postgresql-db-data:
  pgadmin-data:
