version: "3.8"
services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql
volumes:
  mysql-db-data:
